# Chapter 3 Stuff

In [17]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
%cd ~/Physics 331/Textbook Programs/Chapter 3
%ls

/home/cody/Physics 331/Textbook Programs/Chapter 3
efld_mag2.py  efld.py  requirements.txt  Untitled.ipynb


In [23]:
# %load efld.py
def efld(x):
    """
    Finds the electric field from three point charges located at (0,0), (1,0), and (0,0.5).

    Input
    ----------
    x:  Point where I want to find the electric field. This needs to be a two
        point list or array [x,y].

    Output
    ----------
    e: Electic field at point x. [E_x, E_y]

    """

    eps0 = 8.8542e-12 #Permittivity of free space (F/m)

    xa = np.array([0.0, 0.0])    #Possitions of charge 'a' (m)
    qa = 1.0                #Charge of 'a' (C)

    xb = np.array([1.0, 0.0])
    qb = 3.0

    xc = np.array([0.0, 0.5])
    qc = -4.0

    ra = x - xa
    rb = x - xb
    rc = x - xc

    ra_mag = np.sqrt(ra[0]**2 + ra[1]**2)
    rb_mag = np.sqrt(rb[0]**2 + rb[1]**2)
    rc_mag = np.sqrt(rc[0]**2 + rc[1]**2)

    e = (qa * ra / ra_mag**3 + qb * rb / rb_mag**3 + qc * rc / rc_mag**3) / (4 * np.pi * eps0) #Electric field (N/C)
    return e


In [12]:
ep = efld(np.array([.5,.5]))
print(ep)

[-1.69221231e+11  5.08412006e+10]


In [8]:
x = [1,2,3]
y = np.array([1,2,3])
x - y

array([0, 0, 0])

In [24]:
# %load efld_mag2.py
"""
This first line is telling python to look at the file efld.py. Inside that file
there should be a function called efld. Without this first line the program wont 
know what do to when I try and call efld.
"""
def efld_mag2(x):
    """
    I want to find the magnitude of the electric field for the arrangment of
    charged particles given in the program efld.py

    Input
    ----------
    x:  Two element array (x(0) = x value, x(1) = y value) of where I want to
        find the magnitude of the electric field.

    Output
    ----------
    mag: magnitude of the electric field evaluated at the input point 'x'
    """

    e = efld(x)
    mag = e[0]**2 + e[1]**2
    return mag


In [15]:
import scipy.optimize

In [43]:
x0 = scipy.optimize.fmin(efld_mag2, np.array([1.5,0.9]), xtol = 1e-7, ftol = 1e-7)
x01 = scipy.optimize.fmin(efld_mag2, np.array([0.5,0.0]), xtol= 1e-5, ftol = 1e-5)

Optimization terminated successfully.
         Current function value: 0.000004
         Iterations: 122
         Function evaluations: 231


In [44]:
print(x0, x01)

[5.39417785e+16 6.02445501e+15] [ 0.26391312 -0.19112457]


In [42]:
print(efld(x0),efld(x01))

[ 5.18865006e-05 -2.39476157e-05] [-0.00181603  0.00106966]


In [28]:
efld(x0 + [0.001,0])

array([-4.1708356e+08,  2.3493481e+08])

In [29]:
efld(x0 + [0,0.001])

array([2.37261825e+08, 1.86243447e+08])