In [1]:
x = 2

# This is a Title
WOrds and stuff

In [3]:
x = 1

In [4]:
x

1

In [5]:
y = 2

In [6]:
x + y

3

In [7]:
y * 3

6

In [8]:
y /7

0.2857142857142857

In [13]:
y**2 

36

In [11]:
x = 1
y = 3
z = x+ y
print(z)

4


In [12]:
y = 6

In [14]:
z = sin(2)

NameError: name 'sin' is not defined

In [23]:
import numpy as np

In [16]:
z = numpy.sin(numpy.pi)

In [24]:
bobthebuilder.sin(bobthebuilder.pi) #We imported numpy as bobthebuilder

1.2246467991473532e-16

In [18]:
import math

In [19]:
a = math.sin(math.pi)

In [20]:
a

1.2246467991473532e-16

In [25]:
#These are the three main libraries we are going to be using. If you downloaded anaconda they will be on 
#On your computer if they are not, come see me
import numpy as np
import matplotlib.pyplot as plt
import scipy

In [26]:
foo = [1,2,3,4,5]

In [27]:
foo

[1, 2, 3, 4, 5]

In [28]:
bar = [ 5,4,3,2,1]

In [29]:
bar

[5, 4, 3, 2, 1]

In [30]:
foo / bar #can't do math with lists

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [31]:
foo = np.array([1,2,3]) #we can do math with numpy arrays

In [32]:
foo / 2

array([0.5, 1. , 1.5])

In [33]:
#for 'element' in 'object'
for n in foo:
    print(n)

1
2
3


In [34]:
len(foo)

3

In [35]:
foo[1]

2

In [36]:
foo

array([1, 2, 3])

In [37]:
#Arrays start at zero. 
foo[0]

1

In [40]:
print(range(4))

range(0, 4)


In [43]:
#Example of how range works, notice it doens't print out 4
for i in range(4):
    print(i)

0
1
2
3


In [44]:
#how to get the last element of an array
foo[-1]

3

In [45]:
#How to get the second to last element of an array
foo[-2]

2

In [46]:
foo[-3]

1

In [47]:
foo[-4]

IndexError: index -4 is out of bounds for axis 0 with size 3

In [49]:
for i in range(len(foo)):
    #foo[i] += 1
    foo[i] = foo[i] + 1 #Remember that the computer takes what's on the right hand side of the equals sign and,
                        #sets it equal to what's on the left hand side. 
print(foo)

[3 4 5]


In [50]:
z = 8

In [51]:
8 = z

SyntaxError: can't assign to literal (<ipython-input-51-b21d9f9474cd>, line 1)

The if statment always evaluates the thing next to it as True or False. Python checks the thing in the 'if' statment. When it's True, it will do the things inside the statment, when it's Flase it will do what ever is in the else statment. 

In [56]:
if 9 < 5:
    print('This is the best class ever!!!') #Strings can be wrapped in either single or double quotes. 
else:
    print("No it's not!!!")

No it's not!!!


In [57]:
Foo = 3

In [58]:
print(Foo, foo)

3 [3 4 5]


In [59]:
True 

True

In [60]:
False 

False

In [61]:
false = True #Fixed the typo

In [63]:
print(false)

True


In [64]:
print('This is the array foo', foo)

This is the array foo [3 4 5]


In [65]:
blob = ['Cody', 3, 'Is ok at teaching']

In [66]:
for thing in blob: 
    print(thing)

Cody
3
Is ok at teaching


For loops work with element in object

    for element in object:
        do stuff

In [67]:
def my_function(x, y):
    z = x + y
    return z

In [68]:
my_function(1,2)

3

In [69]:
bob = my_function(1,2)

In [70]:
bob

3

In [71]:
def my_func2(x,y):
    for n in x:
        for j in y:
            print(j)
        print(n)
    return True

In [72]:
x = [1,2,3]
y = [3,2,1]
my_func2(x,y)

3
2
1
1
3
2
1
2
3
2
1
3


True

In [73]:
4%2 #modules, or the remainder. 

0

In [74]:
4%3

1

In [78]:
def even_numbers(x):
    return x%2 == 0 #Double equals is a Truth statment, it will be either True or False.

In [79]:
even_numbers(3)

False

In [80]:
even_numbers(1298741289741294)

True

In [81]:
3 > 4

False

In [82]:
3 < 4

True

In [86]:
3 != 3 # ! is the not statment in Python. 3 not equal to 3 is False

False